db:
  type          : MySQL
  install       : Yes
  host          : localhost
  sys_password  : Welcome1
  port          : 49500
  sid           : ovs 
  mgmt_port     : 8080
  user          : ovs
  password      : Welcome1
    
webLogic:
  install       : Yes
  user          : weblogic
  password      : Welcome1
      
java:
  install       : Yes
        
ADF:
  install       : Yes
          
OVMCore:
  install        : Yes
  user           : admin
  password       : Welcome1
  
OVMConsole:
  install       : Yes
  
OVMShell:
  install       : Yes
                
onFailure:
  cleanup       : Yes
  
OVMUpgrade:
  install       : Yes

